apiVersion: stash.appscode.com/v1beta1
kind: RestoreSession
metadata:
  name: ss-restore
  namespace: demo
spec:
  repository:
    name: s3-repo
  rules:
  - paths:
    - /my/data
  hooks:
    preRestore:
      exec:
        command: ["/bin/sh","-c","rm -rf /my/data/*"]
      containerName: stash-init
  target:
    ref:
      apiVersion: apps/v1
      kind: StatefulSet
      name: stash-demo
    volumeMounts:
    - name:  data-volume
      mountPath:  /my/data
